trackingApp/urls.py
from django.urls import path
from . import views
from trackingApp.views import NoteListView, NoteDetailView, CreateNoteView, CreateTaskView, TaskListView,RegisterView ,LoginView ,LogoutView,TaskDetailView, TaskUpdateView, TaskDeleteView, AddCommentToTaskView, EditCommentView, DeleteCommentView

# Для media
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),  # URL-шлях до головної сторінки
    # інші URL-шляхи тут
    path('notes/', NoteListView.as_view(), name='note_list'),
    path('notes/<int:pk>/', NoteDetailView.as_view(), name='note_detail'),
    path('create-note/', CreateNoteView.as_view(), name='create_note'),
    
    path('tasks/', TaskListView.as_view(), name='task_list'),
    path('tasks/<int:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('create-task/', CreateTaskView.as_view(), name='create_task'),

    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('tasks/<int:pk>/update/', TaskUpdateView.as_view(), name='task_update'),
    path('tasks/<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),

    path('tasks/<int:pk>/add-comment/', AddCommentToTaskView.as_view(), name='add_comment'),
    path('tasks/<int:pk>/edit-comment/<int:comment_pk>/', EditCommentView.as_view(), name='edit_comment'),
    path('tasks/<int:pk>/delete-comment/<int:comment_pk>/', DeleteCommentView.as_view(), name='delete_comment'),

    path('success/', views.success, name='success'),
    path('denied/', views.denied, name='denied'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trackingProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trackingApp.urls'))
]

trackingApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    STATUS_CHOICES = [
        ('TODO', 'To Do'),
        ('IN_PROGRESS', 'In Progress'),
        ('DONE', 'Done'),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='TODO')
    PRIORITY_CHOICES = [
        ('LOW', 'Low'),
        ('MEDIUM', 'Medium'),
        ('HIGH', 'High'),
    ]
    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES, default='LOW')
    created_at = models.DateTimeField(auto_now_add=True)
    due_date = models.DateField()
    creator = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    task = models.ForeignKey(Task, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    photo = models.ImageField(upload_to='comment_photos/', null=True, blank=True)

    def __str__(self):
        return f'Comment by {self.user.username} on {self.task.title}'

class Note(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class NoteComment(models.Model):
    note = models.ForeignKey(Note, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.user.username} on {self.note.title}'

trackingApp/forms.py
from django import forms
from trackingApp.models import Task, User, Comment
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["title", "description","status","priority","due_date"]


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

class TaskUpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'status', 'priority', 'due_date']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text', 'photo']

trackingApp/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, DetailView

from django import forms
from trackingApp.forms import TaskForm, UserRegistrationForm, UserLoginForm, TaskUpdateForm, CommentForm
from django.contrib.auth import login, authenticate, logout
from django.views.generic.base import RedirectView

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.views.generic.base import RedirectView
from django.urls import reverse_lazy
from django.views import View
from django.http import HttpResponse

from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin, AccessMixin
from django.http import HttpResponseRedirect

from django.shortcuts import get_object_or_404
from django.contrib import messages

from trackingApp.models import *
# Create your views here.
def index(request):
    return render(request, 'trackingApp/index.html')

class CheckUserInSessionMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_authenticated

    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse_lazy('denied'))
        return super().handle_no_permission()
    
class TaskListView(ListView):
    model = Task
    template_name = 'trackingApp/task_list.html'
    context_object_name = 'tasks'

class TaskDetailView(DetailView):
    model = Task
    template_name = 'trackingApp/task_detail.html'
    context_object_name = 'task'

class NoteListView(ListView):
    model = Note
    template_name = 'trackingApp/note_list.html'
    context_object_name = 'notes'


class NoteDetailView(DetailView):
    model = Note
    template_name = 'trackingApp/note_detail.html'
    context_object_name = 'note'

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'content']


def create_note(request):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('note_list')
    else:
        form = NoteForm()
    return render(request, 'trackingApp/create_note.html', {'form': form})

class CreateNoteView(View):
    def get(self, request):
        form = NoteForm()
        return render(request, 'trackingApp/create_note.html', {'form': form})

    def post(self, request):
        form = NoteForm(request.POST)
        if form.is_valid():
            return HttpResponse("Замітка успішно створена!")
        else:
            return render(request, 'trackingApp/create_note.html', {'form': form})



class CreateTaskView(CheckUserInSessionMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'trackingApp/create_task.html'
    success_url = reverse_lazy('success')

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)

# register, login, logout #
class RegisterView(FormView):
    template_name = 'trackingApp/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('success')

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=raw_password)
        auth_login(self.request, user)
        return super().form_valid(form)

class LoginView(FormView):
    template_name = 'trackingApp/login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('success')

    def form_valid(self, form):
        user = form.get_user()
        auth_login(self.request, user)
        return super().form_valid(form)

class LogoutView(RedirectView):
    url = reverse_lazy('index')

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return super().get(request, *args, **kwargs)

def success(request):
    return render(request, 'trackingApp/success.html')

def denied(request):
    return render(request, 'trackingApp/denied.html')



# Перевірки, чи є користувач автором задачі або суперкористувачем
def is_creator_or_superuser(user, task):
    return user.is_superuser or user == task.creator

# Перевірка користувача перед видаленням або редагуванням завдання
class CheckTaskPermissionMixin(UserPassesTestMixin):
    def test_func(self):
        task = self.get_object()
        return is_creator_or_superuser(self.request.user, task)
    
    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse_lazy('denied'))
        return HttpResponseRedirect(reverse_lazy('denied'))

# Редагування завдання
class TaskUpdateView(CheckTaskPermissionMixin, UpdateView):
    model = Task
    form_class = TaskUpdateForm
    template_name = 'trackingApp/task_update_form.html'
    success_url = reverse_lazy('success')

# Видалення завдання
class TaskDeleteView(CheckTaskPermissionMixin, DeleteView):
    model = Task
    success_url = reverse_lazy('success')




# Коментарі

# Перевірка користувача перед видаленням або редагуванням коментарів

class CheckPermissionMixin(UserPassesTestMixin):
    def test_func(self):
        obj = self.get_object()
        return self.is_creator_or_superuser(self.request.user, obj)

    def is_creator_or_superuser(self, user, obj):
        raise NotImplementedError("is_creator_or_superuser must be implemented in subclasses.")

    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse_lazy('denied'))
        return HttpResponseRedirect(reverse_lazy('denied'))

class CheckCommentPermissionMixin(CheckPermissionMixin):
    model = Comment

    def get_object(self):
        task_id = self.kwargs.get('pk')
        comment_id = self.kwargs.get('comment_pk')
        return get_object_or_404(self.model, pk=comment_id, task_id=task_id)

    def is_creator_or_superuser(self, user, comment):
        return user.is_superuser or user == comment.user
    

class AddCommentToTaskView(CheckUserInSessionMixin, View):
    def post(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.task = task
            comment.user = request.user
            comment.save()
            return redirect('task_detail', pk=pk)
        return redirect('task_detail', pk=pk)

    def get(self, request, pk):
        return redirect('task_detail', pk=pk)

class EditCommentView(CheckCommentPermissionMixin, UpdateView):
    model = Comment
    fields = ['text', 'photo']

    def get_success_url(self):
        return reverse_lazy('task_detail', kwargs={'pk': self.object.task.pk})
        
class DeleteCommentView(CheckCommentPermissionMixin, DeleteView):
    model = Comment
    success_url = reverse_lazy('success')

templates/trackingApp/comment_confirm_delete.html
<!-- templates/trackingApp/comment_confirm_delete.html -->
{% extends 'trackingApp/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/trackingApp/task_confirm_delete.css' %}">
{% endblock %}

{% block content %}
<body>
    <h1>Delete Comment</h1>
    <p>Are you sure you want to delete the comment "{{ object }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
</body>
{% endblock %}

templates/trackingApp/comment_form.html
<!-- templates/trackingApp/update_comment.html -->
{% extends 'trackingApp/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/trackingApp/update_comment.css' %}">
{% endblock %}

{% block content %}
<div class="main-content">
    <h2>Edit comment</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Зберегти</button>
      </form>
</div>
{% endblock %}

templates/trackingApp/create_note.html
{% extends 'trackingApp/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/trackingApp/create_note.css' %}">
{% endblock %}

{% block content %}
<div class="main-content">
    create_note
</div>

{% endblock %}

templates/trackingApp/create_task.html
<!-- templates/trackingApp/create_task.html -->
{% extends 'trackingApp/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/trackingApp/create_task.css' %}">
{% endblock %}

{% block content %}
<div class="main-content">
    <h2>Create a New Task</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Task</button>
    </form>
</div>
{% endblock %}

templates/trackingApp/denied.html
<!-- templates/trackingApp/denied.html -->
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
  <style>
    body {
      text-align: center;
      padding: 40px 0;
      background: #EBF0F5;
    }
    h1 {
      color: red;
      font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
      font-weight: 900;
      font-size: 40px;
      margin-bottom: 10px;
    }
    p {
      color: #404F5E;
      font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
      font-size:20px;
      margin: 0;
    }
    i {
      color: red;
      font-size: 100px;
      line-height: 200px;
      margin-left:-15px;
    }
    .card {
      background: white;
      padding: 60px;
      border-radius: 4px;
      box-shadow: 0 2px 3px #C8D0D8;
      display: inline-block;
      margin: 0 auto;
    }
    #timer {
      color: red;
      font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
      font-size: 24px;
    }
  </style>
</head>
<body>
  <div class="card">
    <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
      <i class="checkmark">X</i>
    </div>
    <h1>Denied</h1>
    <p id="timer">Redirecting in 10 seconds...</p>
    <a href="{% url 'index' %}">Back to Home</a>
  </div>

  <!-- JavaScript для автоматичного перенаправлення через 10 секунд -->
  <script>
    var count = 10;
    var timer = setInterval(function() {
      count--;
      document.getElementById("timer").innerHTML = "Redirecting in " + count + " seconds...";
      if (count == 0) {
        clearInterval(timer);
        window.location.href = "{% url 'index' %}";
      }
    }, 1000); // оновлення кожну секунду
  </script>
</body>
</html>

templates/trackingApp/index.html
<!-- templates/trackingApp/index.html -->
{% extends 'trackingApp/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/trackingApp/index.css' %}">
{% endblock %}

{% block content %}
<div class="main-content">
    index
</div>

{% endblock %}

templates/trackingApp/note_detail.html
<!-- templates/trackingApp/note_detail.html -->
{% extends 'trackingApp/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/trackingApp/note_detail.css' %}">
{% endblock %}

{% block content %}
<div class="main-content">
    <h2>Note Details</h2>
    <p>Title: {{ note.title }}</p>
    <p>Content: {{ note.content }}</p>
</div>

{% endblock %}

templates/trackingApp/note_list.html
<!-- templates/trackingApp/note_list.html -->

{% extends 'trackingApp/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/trackingApp/note_list.css' %}">
{% endblock %}

{% block content %}
<div class="main-content">
    <!-- Your note list content goes here -->
    <h1>Note List</h1>
    <ul>
        {% for note in notes %}
            <li>{{ note.title }}</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/trackingApp/register.html
<!-- templates/trackingApp/register.html -->
{% extends 'trackingApp/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/trackingApp/register.css' %}">
{% endblock %}

{% block content %}
<div class="main-content">
    <h2>Registration</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
</div>
{% endblock %}

templates/trackingApp/success.html
<!-- templates/trackingApp/success.html -->
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
  <style>
    body {
      text-align: center;
      padding: 40px 0;
      background: #EBF0F5;
    }
    h1 {
      color: #88B04B;
      font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
      font-weight: 900;
      font-size: 40px;
      margin-bottom: 10px;
    }
    p {
      color: #404F5E;
      font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
      font-size:20px;
      margin: 0;
    }
    i {
      color: #9ABC66;
      font-size: 100px;
      line-height: 200px;
      margin-left:-15px;
    }
    .card {
      background: white;
      padding: 60px;
      border-radius: 4px;
      box-shadow: 0 2px 3px #C8D0D8;
      display: inline-block;
      margin: 0 auto;
    }
    #timer {
      color: #9ABC66;
      font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
      font-size: 24px;
    }
  </style>
</head>
<body>
  <div class="card">
    <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
      <i class="checkmark">✓</i>
    </div>
    <h1>Success</h1> 
    <p id="timer">Redirecting in 10 seconds...</p>
    <a href="{% url 'index' %}">Back to Home</a>
  </div>

  <!-- JavaScript для автоматичного перенаправлення через 10 секунд -->
  <script>
    var count = 10;
    var timer = setInterval(function() {
      count--;
      document.getElementById("timer").innerHTML = "Redirecting in " + count + " seconds...";
      if (count == 0) {
        clearInterval(timer);
        window.location.href = "{% url 'index' %}";
      }
    }, 1000); // оновлення кожну секунду
  </script>
</body>
</html>

templates/trackingApp/task_confirm_delete.html
<!-- templates/trackingApp/task_confirm_delete.html -->
{% extends 'trackingApp/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/trackingApp/task_confirm_delete.css' %}">
{% endblock %}

{% block content %}
<body>
    <h1>Delete Task</h1>
    <p>Are you sure you want to delete the task "{{ object }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
</body>
{% endblock %}

templates/trackingApp/task_detail.html
<!-- templates/trackingApp/task_detail.html -->
{% extends 'trackingApp/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/trackingApp/task_detail.css' %}">
{% endblock %}

{% block content %}
<body>
    <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">{{ task.title }}</h5>
          <p class="card-text">{{ task.description }}</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">{{ task.get_status_display }}</li>
          <li class="list-group-item">{{ task.get_priority_display }}</li>
          <li class="list-group-item">{{ task.created_at }}</li>
          <li class="list-group-item">{{ task.due_date }}</li>
          <li class="list-group-item">{{ task.creator.username }}</li>
        </ul>
        <div class="card-body">
          <a href="{% url 'task_update' task.pk %}" class="card-link bi bi-pen" >Edit</a>
          <a href="{% url 'task_delete' task.pk %}" class="card-link bi bi-file-earmark-x">Delete</a>
        </div>
      </div>    
    
  

    <h2 class = "my-5">Comments:</h2>
    
    <!-- Додавання коментарів -->
    <form method="post" action="{% url 'add_comment' pk=task.pk %}" enctype="multipart/form-data">
      {% csrf_token %}
      <textarea name="text" class="form-control mb-2" placeholder="Add a comment"></textarea>
      <input type="file" name="photo" accept="image/*">
      <button type="submit" class="btn btn-primary">Publish Comment</button>
    </form>

    {% for comment in task.comments.all %}
    <div class="card mb-4" style="width: 18rem;">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">{{ comment.user.username }}</li>
          <li class="list-group-item">{{ comment.text }}</li>
          {% if comment.photo %}
          <li class="list-group-item">
              <img class="img-thumbnail" src="{{ comment.photo.url }}" alt="Comment File">
          </li>
          {% endif %}
        </ul>
        <div class="card-footer">
            <li class="list-group-item">{{ comment.created_at }}</li>
        </div>
        <div>
          <a href="{% url 'edit_comment' pk=task.pk comment_pk=comment.pk %}" class="card-link bi bi-pen">Edit</a>
          <a href="{% url 'delete_comment' pk=task.pk comment_pk=comment.pk %}" class="card-link bi bi-file-earmark-x">Delete</a>
        </div>
    </div>
    {% endfor %}
</body>

{% endblock %}

templates/trackingApp/task_list.html
<!-- templates/trackingApp/task_list.html -->

{% extends 'trackingApp/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/trackingApp/task_list.css' %}">
{% endblock %}

{% block content %}
<body>
    <h1>Task List</h1>
    <ul>
        {% for task in tasks %}
            <li><a href="{% url 'task_detail' task.pk %}">{{ task.title }}</a></li>
        {% endfor %}
    </ul>
</body>
{% endblock %}

templates/trackingApp/task_update_form.html
<!-- templates/trackingApp/task_update_form.html -->
{% extends 'trackingApp/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/trackingApp/task_update_form.css' %}">
{% endblock %}

{% block content %}
<body>
    <h1>Update Task</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Update Task</button>
    </form>
</body>
{% endblock %}